#!/bin/bash
numDirs=$(find . -maxdepth 1 -type d ! -name ".*" | wc -l)
numSubDirs=$(find . -mindepth 2 -type d ! -name ".*" | wc -l)
totalDirs=$(($numDirs + $numSubDirs))
echo "Total number of directories and sub-directories: $totalDirs"
